# Generated by Django 2.2.7 on 2020-01-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
