# Generated by Django 2.2.7 on 2020-01-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0005_auto_20200125_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
