# Generated by Django 2.2.7 on 2020-02-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0007_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='Review',
        ),
        migrations.AddField(
            model_name='review',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
