# Generated by Django 2.2.7 on 2020-02-02 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0008_auto_20200202_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 13, 37, 22, 600442, tzinfo=utc)),
        ),
    ]
