# Generated by Django 2.2.7 on 2020-02-13 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0014_auto_20200203_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Ecommerce.Product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 13, 12, 18, 0, 587228, tzinfo=utc)),
        ),
    ]
