# Generated by Django 2.2.7 on 2020-02-13 12:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0015_auto_20200213_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='Ecommerce.Product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 13, 12, 19, 41, 612138, tzinfo=utc)),
        ),
    ]
