# Generated by Django 2.2.7 on 2020-02-14 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0017_auto_20200213_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='foruser',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.Product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 8, 53, 55, 173916, tzinfo=utc)),
        ),
    ]
