# Generated by Django 2.2.7 on 2020-02-15 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0019_auto_20200214_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 10, 39, 0, 192440, tzinfo=utc)),
        ),
    ]
