# Generated by Django 3.0.6 on 2020-06-27 18:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0025_auto_20200625_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 18, 29, 1, 750503, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='for_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_product', to='Ecommerce.Product'),
        ),
    ]
